# Services
services:
  # db service
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    hostname: db
    restart: always
    healthcheck:
      test: "mongosh -u superuser -p superuser --authenticationDatabase admin --quiet --eval 'rs.status().ok && rs.isMaster().ismaster'"
      interval: 10s
      timeout: 30s
      start_period: 50s
      retries: 10
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    command: ["-f", "/etc/mongod.conf"]
    networks:
      - my-network

  # Zookeeper service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc -w 2 localhost 2181 | grep imok"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my-network

  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT_EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - my-network
  
  # Order microservice
  order-microservice:
    build:
      context: ./backend
      dockerfile: ./OrderMicroservice/Dockerfile
    ports:
      - "8090:8090"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://pizzaUser:pizzaPassword@db:27017/pizzaapp
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    container_name: orderM
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
      kafka:
        condition: service_healthy

  # Stock microservice
  stock-microservice:
    build:
      context: ./backend
      dockerfile: ./StockMicroservice/Dockerfile
    ports:
      - "8091:8091"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_GROUP_ID: stock
      KAFKA_AUTO_OFFSET_RESET: earliest
    container_name: stockM
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
      kafka:
        condition: service_healthy
    
  # Email microservice
  email-microservice:
    build:
      context: ./backend
      dockerfile: ./EmailMicroservice/Dockerfile
    ports:
      - "8092:8092"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONSUMER_GROUP_ID: email
      KAFKA_AUTO_OFFSET_RESET: earliest
    container_name: emailM
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
      kafka:
        condition: service_healthy

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - order-microservice
    networks:
      - my-network

# Volumes definition
volumes:
  db_data:

# Networks definition
networks:
  my-network:
    driver: bridge