# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Set environment variables for MongoDB
ENV MONGO_INITDB_ROOT_USERNAME=Admin
ENV MONGO_INITDB_ROOT_PASSWORD=27bv2%td8!R1/t&ttikIph-xZPi4
ENV MONGO_INITDB_DATABASE=pizza

# Expose the default MongoDB port
EXPOSE 27017

# Custom MongoDB configuration file
# COPY mongod.conf /etc/mongod.conf
# CMD ["mongod", "--config", "/etc/mongod.conf"]

# Default command to run MongoDB
CMD ["mongod"]
